site_name: trivy-operator
site_description: Kubernetes Operator based on the open-source container vulnerability scanner Trivy.
site_url: https://devopstales.github.io/trivy-operator/
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/devopstales/trivy-operator
edit_uri: ""

nav:
    - Overview: index.md
    - Quick Start: quickstart.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Functions:
        - Admission Controller: functions/image-validator.md
    - Integrations:
        - Monitoring: integrations/monitoring.md
        - Policy Reporter: integrations/policy-reporter.md
    - Custom Resource Definitions:
        - Overview: crds/index.md
        - NamespaceScanner: crds/namespace-scanner.md
        - VulnerabilityReport: crds/vulnerability-report.md
        - PolicyReport: crds/policy-report.md


theme:
  name: material
  language: "en"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - def_list
  - pymdownx.details

extra:
  generator: false
  version:
    default: latest
    method: mike
    provider: mike

plugins:
  - search
  - macros
