---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-bench-scnner
  namespace: trivy-operator
spec:
  selector:
    matchLabels:
      app: kube-bench-scnner
  template:
    metadata:
      labels:
        app: kube-bench-scnner
      annotations:
        prometheus.io/port: "9115"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/builder: "true"
      securityContext:
          fsGroup: 10001
          fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: trivy-operator
      hostPID: true
      containers:
      - image: devopstales/kube-bench-scnner:2.5-devel
        imagePullPolicy: IfNotPresent
        name: kube-bench-scnner
        env:
        - name: VERBOSE_LOG
          value: "true"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
          - name: var-lib-etcd
            mountPath: /var/lib/etcd
            readOnly: true
          - name: var-lib-kubelet
            mountPath: /var/lib/kubelet
            readOnly: true
          - name: var-lib-kube-scheduler
            mountPath: /var/lib/kube-scheduler
            readOnly: true
          - name: var-lib-kube-controller-manager
            mountPath: /var/lib/kube-controller-manager
            readOnly: true
          - name: etc-systemd
            mountPath: /etc/systemd
            readOnly: true
          - name: lib-systemd
            mountPath: /lib/systemd/
            readOnly: true
          - name: srv-kubernetes
            mountPath: /srv/kubernetes/
            readOnly: true
          - name: etc-kubernetes
            mountPath: /etc/kubernetes
            readOnly: true
          - name: usr-bin
            mountPath: /usr/local/mount-from-host/bin
            readOnly: true
          - name: etc-cni-netd
            mountPath: /etc/cni/net.d/
            readOnly: true
          - name: opt-cni-bin
            mountPath: /opt/cni/bin/
            readOnly: true
          - name: etc-passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: etc-group
            mountPath: /etc/group
            readOnly: true
        ports:
          - containerPort: 9115
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: "/var/lib/etcd"
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: var-lib-kube-scheduler
          hostPath:
            path: "/var/lib/kube-scheduler"
        - name: var-lib-kube-controller-manager
          hostPath:
            path: "/var/lib/kube-controller-manager"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: lib-systemd
          hostPath:
            path: "/lib/systemd"
        - name: srv-kubernetes
          hostPath:
            path: "/srv/kubernetes"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: usr-bin
          hostPath:
            path: "/usr/bin"
        - name: etc-cni-netd
          hostPath:
            path: "/etc/cni/net.d/"
        - name: opt-cni-bin
          hostPath:
            path: "/opt/cni/bin/"
        - name: etc-passwd
          hostPath:
            path: "/etc/passwd"
        - name: etc-group
          hostPath:
            path: "/etc/group"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-bench-scnner
  name: kube-bench-scnner
  namespace: trivy-operator
spec:
  selector:
    app: kube-bench-scnner
  ports:
    - name: metrics
      protocol: TCP
      port: 9115
      targetPort: 9115
