{
 "title": "Trivy Vulnerabilities",
 "description": "Dashboard for Trivy Vulnerabilities",
 "tags": [
  "Trivy",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "Critical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(so_vulnerabilities{severity=\"CRITICAL\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'critical'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(so_vulnerabilities{severity=\"HIGH\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'high'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(so_vulnerabilities{severity=\"MEDIUM\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'medium'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Low",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(so_vulnerabilities{severity=\"LOW\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'low'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Unkown",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(so_vulnerabilities{severity=\"UNKNOWN\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM host",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Vulneribilities Pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(so_vulnerabilities{}) by(severity)",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{severity}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  $__timeGroupAlias(create_date,336h),\n  ip AS metric,\n  count(id) AS count\nFROM host\nWHERE\n  $__timeFilter(create_date) AND owned = 'true' AND workspace_id=1\nGROUP BY 1,2\nORDER BY 1,2,3",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 17, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(so_vulnerabilities{severity=\"CRITICAL\"}) by (image,exported_namespace)",
     "legendFormat": "B"
    },
    {
     "expr": "sum(so_vulnerabilities{severity=\"HIGH\"}) by (image,exported_namespace)",
     "legendFormat": "B"
    }
   ]
  }
 ]
}