---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-cache
  namespace: trivy-operator
spec:
  selector:
    matchLabels:
      app: trivy-cache
  template:
    metadata:
      labels:
        app: trivy-cache
    spec:
      securityContext:
          fsGroup: 10001
          fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: trivy-operator
      containers:
      - image: redis:latest
        name: redis
        imagePullPolicy: Always
        volumeMounts:
        - name: cache
          mountPath: "/data"
        ports:
          - containerPort: 6379
      volumes:
      - name: cache
        persistentVolumeClaim:
            claimName: "redis-cache"
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: redis-cache
  namespace: trivy-operator
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trivy-cache
  name: trivy-cache
  namespace: trivy-operator
spec:
  selector:
    app: trivy-cache
  ports:
    - name: cache
      protocol: TCP
      port: 6379
      targetPort: 6379
