apiVersion: trivy-operator.devopstales.io/v1
kind: NamespaceScanner
metadata:
  name: main-config
spec:
  crontab: "*/5 * * * *"
  namespace_selector: "trivy-scan"
#  registry:
#  - name: docker.io
#    user: "user"
#    password: "password"
