---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    trivy-scan: "true"
    trivy-operator-validation: "true"
  name: trivytest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: trivytest
spec:
  initContainers:
  - name: init
    image: nginxinc/nginx-unprivileged:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 10']
  - name: init2
    image: nginxinc/nginx-unprivileged:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 10']
  containers:
  - image: nginx:1.18
    imagePullPolicy: IfNotPresent
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: trivytest
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx2
