---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    trivy-scan: "true"
  name: trivytest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: trivytest
spec:
  containers:
  - image: nginx:1.18
    imagePullPolicy: IfNotPresent
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: trivytest
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx