apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog
  namespaces: oml
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: docker.io/devopstales/trivy-operator-index:2.1.1-oc
  updateStrategy:
    registryPoll:
      interval: 1m
