apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    categories: "Security"
    alm-examples: |-
      [
        {
          "apiVersion": "trivy-operator.devopstales.io/v1",
          "kind": "NamespaceScanner",
          "metadata": {
            "name": "trivy-operator-main-config",
            "annotations": {
              "helm.sh/hook": "post-install,post-upgrade"
            }
          },
          "spec": {
            "crontab": "*/5 * * * *",
            "namespace_selector": "trivy-scan",
            "registry": [
              {
                "name": "docker.io",
                "user": "",
                "password": ""
              }
            ]
          }
        }
      ]
  name: trivy-operator.v0.0.1
  namespace: trivy-operator
spec:
  description: |
    Trivy Operator for scheduled scans of images and Admission Control.
    The Operator use Github to download Trivy database. If your Github API Rate Limit Exceeded add your Github token to the operator deployment as GITHUB_TOKEN variable.
    If you want to scan images from a private reposytori edit the operator deployment andd add pull secrets.
  displayName: Trivy Operator
  icon:
  - base64data: ""
    mediatype: "img/png"
  keywords:
  - trivy
  - security
  maintainers:
  - email: devopstales@protonmail.com
    name: devopstales
  maturity: alpha
  provider:
    name: devopstales
    url: devopstales.github.io
  version: 2.1
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
            - "apiextensions.k8s.io"
          resources:
            - "customresourcedefinitions"
          verbs: 
            - "create"
        - apiGroups:
          - "trivy-operator.devopstales.io"
          resources:
          - namespace-scanners
          - namespace-scanners/status
          verbs:
          - get
          - watch
          - list
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - get
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          - namespaces
          verbs:
          - get
          - watch
          - list
        serviceAccountName: trivy-operator
      services:
      - name: trivy-operator
        spec:
          selector:
            app: trivy-operator
          ports:
            - name: metric
              port: 9115
              protocol: TCP
              targetPort: 9115
      - name: trivy-image-validator
        spec:
          selector:
            app: trivy-operator
          ports:
            - name: webhook
              targetPort: 8443
              protocol: TCP
              port: 443
      persistentvolumeclaims:
      - name: trivy-cache
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      deployments:
      - name: trivy-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: trivy-operator
          template:
            metadata:
              labels:
                app: trivy-operator
              annotations:
                prometheus.io/port: "9115"
                prometheus.io/scrape: "true"
            spec:
              imagePullSecrets:
              securityContext:
                fsGroup: 10001
                fsGroupChangePolicy: "OnRootMismatch"
              serviceAccountName: trivy-operator
              containers:
              - name: trivy-operator
                image: "devopstales/trivy-operator:2.1"
                imagePullPolicy: Always
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                volumeMounts:
                - name: cache
                  mountPath: "/home/trivy-operator/trivy-cache"
                ports:
                  - name: metric
                    containerPort: 9115
                    protocol: TCP
                  - name: https
                    containerPort: 8443
                    protocol: TCP
              volumes:
              - name: cache
                persistentVolumeClaim:
                    claimName: trivy-cache
