apiVersion: v1
kind: Namespace
metadata:
  name: trivy-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-operator
rules:
- apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - customresourcedefinitions
  verbs:
    - create
- apiGroups:
    - "apps/v1"
  resources:
    - DaemonSet
  verbs:
    - get
    - create
    - delete
- apiGroups:
   - "wgpolicyk8s.io"
  resources:
  - policyreports
  verbs:
    - get
    - create
    - delete
- apiGroups:
   - "wgpolicyk8s.io"
  resources:
  - clusterpolicyreports
  verbs:
    - get
    - create
    - delete
- apiGroups:
   - "trivy-operator.devopstales.io"
  resources:
  - vulnerabilityreports
  verbs:
    - get
    - create
    - delete
- apiGroups:
   - "trivy-operator.devopstales.io"
  resources:
  - namespace-scanners
  - namespace-scanners/status
  - cluster-scanners
  - cluster-scanners/status
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
   - ""
  resources:
  - events
  verbs:
  - get
  - create
  - patch
- apiGroups:
   - ""
  resources:
  - pods
  - namespaces
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - patch
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-operator
subjects:
- kind: ServiceAccount
  name: trivy-operator
  namespace: trivy-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: trivy-operator
