apiVersion: trivy-operator.devopstales.io/v1
kind: NamespaceScanner
metadata:
  name: main-config
spec:
  crontab: "*/5 * * * *"
  namespace_selector: "trivy-scan"
  clusterWide: "false"
  policyreport: "true"
  airGapped: "false"
  image_pull_secrets:
    - devopstales-dockerhub
#  registry:
#  - name: docker.io
#    user: "devopstales"
#    password: ""
#    insecure: True 
