---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    trivy-scan: "true"
    trivy-operator-validation: "true"
  name: trivytest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: trivytest
spec:
  initContainers:
  - name: init
    image: alpine:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 10']
  - name: init2
    image: ubuntu:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 10']
  containers:
  - image: docker.rancher-decktop.intra/evopstales/demo:insecure
    imagePullPolicy: IfNotPresent
    name: nginx
  - image: library/nginx:bad
    imagePullPolicy: IfNotPresent
    name: nginx-bad
