---
name: "tagged-release"

on:
  push:
    branches:
      - "master"
    tags:
      - "*.*"


jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: trivy-operator-${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
