name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare
        id: prep
        run: |
          VERSION = ${GITHUB_REF#refs/tags/v}
          TRIVY   = $(shell curl --silent https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r .name | cut -d "v" -f2)
          wget -q -O /tmp/trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v$(TRIVY)/trivy_"$(TRIVY)"_Linux-64bit.tar.gz
          tar -C /tmp -xf /tmp/trivy.tar.gz
          # copy files
          cp /tmp/trivy docker/trivy
          cp trivy-operator.py docker/trivy-operator.py
          # Set output parameters.
          echo ::set-output name=tag::${VERSION}
          echo ::set-output name=trivy::${TRIVY}
      - name: Build amd64
        uses: docker/build-push-action@v2
        with:
          context: docker/
          build-args:
            ARCH=amd64/
          tags: devopstales/trivy-operator:${{ steps.prep.outputs.tag }}-amd64
          push: true
      - name: Build arm64v8
        uses: docker/build-push-action@v2
        with:
          context: docker/
          build-args:
            ARCH=arm64v8/
          tags: devopstales/trivy-operator:${{ steps.prep.outputs.tag }}-arm64v8
          push: true
